[sensor]
row = 10
columns = 10
defaultLevel = "GOOD"
timeUnit = "SECONDS"
samplesTime = 900
finalTime = 3600

[[sensor.cell]]
    cellNumber = 62
    level = "MODERATE"
    fromTime = 0
[[sensor.cell]]
    cellNumber = 63
    level = "MODERATE"
    fromTime = 0
[[sensor.cell]]
    cellNumber = 63
    level = "VERY_POOR"
    fromTime = 120
